### ISSUE TITLE
Twitterカードがスタンプ用画像よりも優先的に表示されてしまう

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/cmd-chan#1]
![](https://cloud.githubusercontent.com/assets/5749086/13049819/ce527b70-d432-11e5-8268-43c4419fe39e.jpg)

**Comment by keepoff07** [comment]
現状は
```
ページURL
画像URL
```
の並びで呟くようにしている。
これを逆にしてもTwitterカードは優先されてしまい、
ページURLを短縮URLにしてもTwitterカードは読まれて表示された。
先人の知恵を拝見してもそうだったが、Twitterカードを排除するしかなさそう。

**Comment by keepoff07** [comment]
ただ、今は[index](https://github.com/keepoff07/cmd-chan/blob/master/index.html)にiframeでゴリゴリ表示させてる形なので、
スタンプのページのTwitterカードだけは排除する、と言ったことができない状態です。
全部作りなおすか諦めるかしか思いつかないので助けて

**Comment by 844196** [comment]
色々考えましたが、

* カードを残す場合
    * iframe + jsをJekyllかHugoなりのテンプレートツールで書き換える
        * head（というか各サブページ）をコンポーネントとして扱い、ページごとに埋め込むheadを決める
    * metaタグ自体をページタイトルで判定して埋め込みの可否を動的に決める
        * ただ、twitter側のメタタグ取得のタイミングに合うかはあやC。#3 の結果を見るに、jsは無視しているぽい？
    * スーパーハカーを待つ
* カードを取り払う場合
    * `head`内のmetaタグを消す

**Comment by keepoff07** [comment]
Jekyllに移行させました。
まだ移行状態は中途半端ですが、本件は解決したのでクローズします。
![img_20160317_223423](https://cloud.githubusercontent.com/assets/5749086/13847520/f612e4ee-ec90-11e5-96e1-213ad070c7ec.JPG)

**Comment by 844196** [comment]
![images](https://cloud.githubusercontent.com/assets/4990822/13863216/aed7a4c0-ecdb-11e5-9c45-d27cabf67896.jpg)

確認しました
お疲れさまです
